const COORDINATES_API_CALL_REQUEST = 'COORDINATES_API_CALL_REQUEST';
const COORDINATES_API_CALL_SUCCESS = 'COORDINATES_API_CALL_SUCCESS';
const COORDINATES_API_CALL_FAILURE = 'COORDINATES_API_CALL_FAILURE';

const CITYNAME_API_CALL_REQUEST = 'CITYNAME_API_CALL_REQUEST';
const CITYNAME_API_CALL_SUCCESS = 'CITYNAME_API_CALL_SUCCESS';
const CITYNAME_API_CALL_FAILURE = 'CITYNAME_API_CALL_FAILURE';

const FORECAST_API_CALL_REQUEST = 'FORECAST_API_CALL_REQUEST';
const FORECAST_API_CALL_SUCCESS = 'FORECAST_API_CALL_SUCCESS';
const FORECAST_API_CALL_FAILURE = 'FORECAST_API_CALL_FAILURE';


const HISTORY = 'HISTORY';
const DETAIL = 'DETAIL';
const HOME = 'HOME';

const SAVE_SEARCH_WORD = 'SAVE_SEARCH_WORD';

export {
  COORDINATES_API_CALL_REQUEST,
  COORDINATES_API_CALL_SUCCESS,
  COORDINATES_API_CALL_FAILURE,

  CITYNAME_API_CALL_REQUEST,
  CITYNAME_API_CALL_SUCCESS,
  CITYNAME_API_CALL_FAILURE,

  FORECAST_API_CALL_REQUEST,
  FORECAST_API_CALL_SUCCESS,
  FORECAST_API_CALL_FAILURE,

  HISTORY,
  DETAIL,
  HOME,

  SAVE_SEARCH_WORD
};
